apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: ${BASE_NAME}
spec:
 type: 0
 ResourceID: /subscriptions/${ARM_SUBSCRIPTION_ID}/resourcegroups/${NODE_RESOURCE_GROUP}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${BASE_NAME}
 ClientID: ${IDENTITY_CLIENT_ID}